name: CI

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: details-service

jobs:
  build:
    name: Build Bookinfo details image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}    

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          file: /samples/bookinfo/src/details/
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest
      
